### PR TITLE
Fix SystemError: PyEval_EvalFrameEx returned a result with an error set (#97)

### PR DESCRIPTION
**Pull request by lerela**
I don't know if this is the proper way to fix the issue, but it seems that calling PyObject functions while there is an ongoing exception fails. So store the exception, run the PyObject functions, then restore it.

### CODE REVIEW

**Comment by ngie-eign** [comment]
@lerela: I don't know if this is still valid in light of #117.

**Comment by lerela** [comment]
@ngie-eign: I'm not entirely sure #117 would fix it as reporters of #108 mention that downgrading to 3.6 solves it for them, yet issue #97 is about a crash on 3.6 so there's possibly something else going on. However I can't test it anymore, so feel free to close the PR if it's obsolete!

**Comment by maxyou2090** [comment]
Great, This works for me

last：returned NULL without setting an error

now：EasySNMPTimeoutError('timed out while connecting to remote host')

My version is 3.7.6

**Comment by ngie-eign** [comment]
@kamakazikamikaze: could you please look at this change once @lerela rebases their branch (the Travis CI issues are all linker related)?

**Comment by kamakazikamikaze** [comment]
Apologies, I saw PR #129 and pulled that before reviewing this one. Thank you for having spent the time troubleshooting and submitting a fix.

**Pull request closed without merging**
